runtime: custom
api_version: '1.0'
env: flexible
threadsafe: true
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 3
  cpu_utilization:
    target_utilization: 0.5
resources:
  cpu: 1
  memory_gb: 1
  disk_size_gb: 15
health_check:
  enable_health_check: false
